version: '3.8'
services:
  poa:
    container_name: TBWG-NODE-00
    image: ethereum/client-go
    restart: always
    working_dir: /poa
    hostname: TBWG-NODE-00
    volumes:
      - $PWD:/poa
    ports:
      - 30333:30333
    command: | 
      --networkid 35
      --syncmode "full" 
      --mine
      --miner.gasprice 10000000000
      --datadir "node" 
      --nousb 
      --password password.txt
      --unlock 0x0001111222233334444555566667777888899999
      --port 30333 
      --bootnodes "enode://f17da7e240aabea9297e84396a564f092345a551bfdf38ea1f558559b6874ed6d04a6b4b04ee153e2c30dd011f302a41093239399f95b8dfe5d845b63e63f745@103.27.203.74:30555,enode://f17da7e240aabea9297e84396a564f092345a551bfdf38ea1f558559b6874ed6d04a6b4b04ee153e2c30dd011f302a41093239399f95b8dfe5d845b63e63f745@103.27.203.74:30555,enode://a286a1972ca88a98a7762a32f9203459757cde23f3021866f0fb27db7d4ccc37d09528d906bb9642e9b7081e648c16d4a2ca579eecc64e3a9d7cec9d7e4c1588@103.27.203.74:30333,enode://2bc587783dc443950ca957ae8260bb3da07b3fe9a266d8dccc35a4f6ebbc514748d582b57008c45b9122f827fa17b08cfd93357888e0b81757ff1b2c202fd59a@52.237.108.90:30333,enode://f6b81f0b9f6535a8013c75d8b15b488a3b0c13eb37ed49e0b67e34fc52a4c06443d4660b26ae9a5962715b52a63ce2702808b4f1ba64da865fadedc2a9860585@210.1.62.206:30333"

